-- MySQL Script generated by MySQL Workbench
-- Wed Apr  3 10:11:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Jiceda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Jiceda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Jiceda` DEFAULT CHARACTER SET utf8 ;
USE `Jiceda` ;

-- -----------------------------------------------------
-- Table `Jiceda`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jiceda`.`Users` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NULL,
  `password` VARCHAR(30) NULL,
  `lastname` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `email` VARCHAR(55) NULL,
  `registrationdate` DATE NULL,
  `profilpic` VARCHAR(100) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jiceda`.`Messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jiceda`.`Messages` (
  `idmessage` INT NOT NULL AUTO_INCREMENT,
  `messagecontent` VARCHAR(255) NULL,
  `messagedate` DATETIME NULL,
  PRIMARY KEY (`idmessage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jiceda`.`Posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jiceda`.`Posts` (
  `idpost` INT NOT NULL AUTO_INCREMENT,
  `postcontent` VARCHAR(255) NULL,
  `postdate` DATETIME NULL,
  `Users_iduser` INT NOT NULL,
  PRIMARY KEY (`idpost`),
  INDEX `fk_Posts_Users1_idx` (`Users_iduser` ASC),
  CONSTRAINT `fk_Posts_Users1`
    FOREIGN KEY (`Users_iduser`)
    REFERENCES `Jiceda`.`Users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jiceda`.`Friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jiceda`.`Friends` (
  `idfriend` INT NOT NULL AUTO_INCREMENT,
  `Users_iduser` INT NOT NULL,
  INDEX `fk_Friends_Users1_idx` (`Users_iduser` ASC),
  PRIMARY KEY (`idfriend`),
  CONSTRAINT `fk_Friends_Users1`
    FOREIGN KEY (`Users_iduser`)
    REFERENCES `Jiceda`.`Users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jiceda`.`Receive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jiceda`.`Receive` (
  `Messages_idmessage` INT NOT NULL,
  `Friends_idfriend` INT NOT NULL,
  INDEX `fk_Recevoir_messages1_idx` (`Messages_idmessage` ASC),
  INDEX `fk_Receive_Friends1_idx` (`Friends_idfriend` ASC),
  CONSTRAINT `fk_Recevoir_messages1`
    FOREIGN KEY (`Messages_idmessage`)
    REFERENCES `Jiceda`.`Messages` (`idmessage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receive_Friends1`
    FOREIGN KEY (`Friends_idfriend`)
    REFERENCES `Jiceda`.`Friends` (`idfriend`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jiceda`.`Send`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jiceda`.`Send` (
  `Messages_idmessage` INT NOT NULL,
  `Friends_idfriend` INT NOT NULL,
  INDEX `fk_Envoyer_messages1_idx` (`Messages_idmessage` ASC),
  INDEX `fk_Send_Friends1_idx` (`Friends_idfriend` ASC),
  CONSTRAINT `fk_Envoyer_messages1`
    FOREIGN KEY (`Messages_idmessage`)
    REFERENCES `Jiceda`.`Messages` (`idmessage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Send_Friends1`
    FOREIGN KEY (`Friends_idfriend`)
    REFERENCES `Jiceda`.`Friends` (`idfriend`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jiceda`.`Subscribers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jiceda`.`Subscribers` (
  `idsubscriber` INT NOT NULL AUTO_INCREMENT,
  `Users_iduser` INT NOT NULL,
  INDEX `fk_Subscribers_Users1_idx` (`Users_iduser` ASC),
  PRIMARY KEY (`idsubscriber`),
  CONSTRAINT `fk_Subscribers_Users1`
    FOREIGN KEY (`Users_iduser`)
    REFERENCES `Jiceda`.`Users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jiceda`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jiceda`.`Questions` (
  `idQuestion` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(255) NULL,
  PRIMARY KEY (`idQuestion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Jiceda`.`Commentaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jiceda`.`Commentaires` (
  `idCommentaire` INT NOT NULL AUTO_INCREMENT,
  `Commentaire` VARCHAR(255) NULL,
  `Questions_idQuestion` INT NOT NULL,
  `Users_iduser` INT NOT NULL,
  PRIMARY KEY (`idCommentaire`),
  INDEX `fk_Commentaires_Questions1_idx` (`Questions_idQuestion` ASC),
  INDEX `fk_Commentaires_Users1_idx` (`Users_iduser` ASC),
  CONSTRAINT `fk_Commentaires_Questions1`
    FOREIGN KEY (`Questions_idQuestion`)
    REFERENCES `Jiceda`.`Questions` (`idQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commentaires_Users1`
    FOREIGN KEY (`Users_iduser`)
    REFERENCES `Jiceda`.`Users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
