INSERT INTO Questions(question) VALUES ('Faut-il rétablir l''ISF ?');
INSERT INTO Questions(question) VALUES ('Les casseurs ont-ils cassé le mouvement des Gillets Jaunes ?');
INSERT INTO Questions(question) VALUES ('La religion est-elle un obstacle entre l''homme et la femme ?');
INSERT INTO Questions(question) VALUES ('Faut-il interdire tous les écrans dans les écoles et dans les collèges ?');
INSERT INTO Questions(question) VALUES ('Les concours de beauté favorisent-ils le concept de femme objet ?');
INSERT INTO Questions(question) VALUES ('Peut-on vivre sans plastique ?');
INSERT INTO Questions(question) VALUES ('Les droits de l’homme sont-ils « universels » ?');
INSERT INTO Questions(question) VALUES ('La conquête spatiale a-t-elle encore un sens ?');
INSERT INTO Questions(question) VALUES ('La lutte contre la pollution doit-elle passer par une hausse de la fiscalité ?');
INSERT INTO Questions(question) VALUES ('Avortement : faut-il supprimer la clause de conscience pour les médecins ?');
INSERT INTO Questions(question) VALUES ('Faut-il restreindre l’immigration en France ?');
INSERT INTO Questions(question) VALUES ('Prostitution : faut-il légaliser le travail sexuel ?');
INSERT INTO Questions(question) VALUES ('Une agriculture sans pesticides est-elle possible ?');
INSERT INTO Questions(question) VALUES ('Pour ou contre un « SMIC » européen ?');
INSERT INTO Questions(question) VALUES ('Faut-il rétablir la peine de mort ?');
INSERT INTO Questions(question) VALUES ('Le cannabis thérapeutique doit-il être légal ?');
INSERT INTO Questions(question) VALUES ('Faut-il arrêter de manger de la viande pour sauver la planète ?');
INSERT INTO Questions(question) VALUES ('L’Eglise catholique doit-elle autoriser les femmes à devenir prêtres ?');
INSERT INTO Questions(question) VALUES ('La démocratie est-elle morte ?');